#!/usr/bin/env bash
#where I found this script originally 
#https://github.com/netson/ubuntu-unattended
#I changed some things around and added what I wanted it to do
#file names & paths
tmp="/tmp"  # destination folder to store the final iso file
#hostname="ubuntu" #I wanted user to choose hostname
currentuser="$( whoami)"

# define spinner function for slow tasks
# courtesy of http://fitnr.com/showing-a-bash-spinner.html
spinner()
{
    local pid=$1
    local delay=0.75
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}

# define download function
# courtesy of http://fitnr.com/showing-file-download-progress-using-wget.html
download()
{
    local url=$1
    echo -n "    "
    wget --progress=dot $url 2>&1 | grep --line-buffered "%" | \
        sed -u -e "s,\.,,g" | awk '{printf("\b\b\b\b%4s", $2)}'
    echo -ne "\b\b\b\b"
    echo " DONE"
}

# define function to check if program is installed
# courtesy of https://gist.github.com/JamieMason/4761049
function program_is_installed {
    # set to 1 initially
    local return_=1
    # set to 0 if not found
    type $1 >/dev/null 2>&1 || { local return_=0; }
    # return value
    echo $return_
}

# print a pretty header
echo
echo " +---------------------------------------------------+"
echo " |     UNATTENDED UBUNTU or Custom ISO MAKER         |"
echo " +---------------------------------------------------+"
echo

# ask if script runs without sudo or root priveleges
if [ $currentuser != "root" ]; then
    echo " you run this without sudo privileges or not as root"
    exit 1
fi

# ask whether to include vmware tools or not
while true; do
    echo " which ubuntu edition would you like to remaster:"
    echo
    echo "  [1] Ubuntu 16.04.2 LTS Server amd64 - Xenial Xerus"
    echo "  [2] Choose your own iso file with the absolte path"
    echo
    read -p " please enter your preference: [1|2]: " ubver
    case $ubver in
        [1]* )  download_file="ubuntu-16.04.2-server-amd64.iso"
                download_location="http://releases.ubuntu.com/16.04/"
                new_iso_name="ubuntu-16.04.2-server-amd64-unattended.iso"
                break;;
	[2]* )  read -p "Please give me your absolute path for your iso:" isop
		iso=$(basename $isop)
		echo ""Please give me the name of what you want your iso to be.
		read -p "Do not forget the .iso:" ison
		download_file=$iso
		download_location="There will not be a location"
		new_iso_name=$ison
		if [[ ! -f $tmp/$download_file ]]; then
    		echo " copying $download_file "
    		cp -r $isop $tmp
		fi
		break;;
        * ) echo " please answer [1] or [2]";;
    esac
done

if [ -f /etc/timezone ]; then
  timezone=`cat /etc/timezone`
elif [ -h /etc/localtime]; then
  timezone=`readlink /etc/localtime | sed "s/\/usr\/share\/zoneinfo\///"`
else
  checksum=`md5sum /etc/localtime | cut -d' ' -f1`
  timezone=`find /usr/share/zoneinfo/ -type f -exec md5sum {} \; | grep "^$checksum" | sed "s/.*\/usr\/share\/zoneinfo\///" | head -n 1`
fi

# ask the user questions about his/her preferences
read -ep " please enter your preferred timezone: " -i "${timezone}" timezone
read -ep " please enter your preferred username: " -i "jeff" username
read -ep " please enter your preferred hostname: " -i "ubuntu" hostname
read -ep " please enter your preferred domain-name: " -i "mydomain.com" domain
read -sp " please enter your preferred password: " upassword
printf "\n"
read -sp " confirm your preferred password: " upassword2
printf "\n"
# check if the passwords match to prevent headaches
if [[ "$upassword" != "$upassword2" ]]; then
    echo " your passwords do not match; please restart the script and try again"
    echo
    exit
fi
read -sp " please enter your preferred root password: " rpassword
printf "\n"
read -sp " confirm your root password: " rpassword2
printf "\n"
# check if the passwords match to prevent headaches
if [[ "$rpassword" != "$rpassword2" ]]; then
    echo " your passwords do not match; please restart the script and try again"
    echo
    exit
fi

read -ep " Make ISO bootable via USB: " -i "yes" bootable
read -ep " Would you like to make a bootable disk with dd: " -i "yes" usedd
if [[ $usedd == "yes" ]] || [[ $usedd == "y" ]]; then
  echo " Please use full disk name ie /dev/sdc without partition"
  read -p "What disk would you like to use:" disk
fi
echo 
#answers for installing applications
read -ep "Would you like to install nmap, vim-nox, and python3-pip with this iso:" -i "yes" nmapin
#read -ep "Would you like to isntall on disk or lvm:" -i "lvm" lvmm  haven't got to building this option yet
#if [[ $lvmm == "lvm" ]] || [[ $lvmm == "lv" ]]; then
#  echo " Please use full disk name ie /dev/sdc without partition"

#fi


# download the ubunto iso
cd $tmp
if [[ ! -f $tmp/$download_file ]]; then
    echo -n " downloading $download_file: "
    download "$download_location$download_file"
fi
if [[ ! -f $tmp/$download_file ]]; then
	echo "Error: Failed to download ISO: $download_location$download_file"
	echo "This file may have moved or may no longer exist."
	echo
	echo "You can download it manually and move it to $tmp/$download_file"
	echo "Then run this script again."
	exit 1
fi

# download netson seed file
while true; do
    echo "What preseed file would you like to use?:"
    echo
    echo " [1] Suggested use jeff's preseed file"
    echo " [2] Choose your own preseed file"
    echo
    read -p " please enter your preference: [1|2]: " preseed
    case $preseed in
        [1]* )  seed_file="preseed.cfg"
		if [[ ! -f $tmp/$seed_file ]]; then
		echo -n " downloading $seed_file: "
		download "https://raw.githubusercontent.com/jeffrolinux/unattendedinstall/master/$seed_file"
		fi
                break;;
        [2]* )  read -p "Please give me the absolute path of the preseed file:" prep
		pre=$(basename $prep)
		seed_file=$pre
		if [[ ! -f $tmp/$seed_file ]]; then
                cp -r $prep $tmp
                fi
                break;;
        * ) echo " please answer [1] or [2]";;
    esac
done


#seed_file="preseed.cfg"
#if [[ ! -f $tmp/$seed_file ]]; then
#    echo -n " downloading $seed_file: "
#    download "https://raw.githubusercontent.com/netson/ubuntu-unattended/master/$seed_file"
#fi

# install required packages
echo " installing required packages"
if [ $(program_is_installed "mkpasswd") -eq 0 ] || [ $(program_is_installed "mkisofs") -eq 0 ]; then
    (apt-get -y update > /dev/null 2>&1) &
    spinner $!
    (apt-get -y install whois genisoimage > /dev/null 2>&1) &
    spinner $!
fi
if [[ $bootable == "yes" ]] || [[ $bootable == "y" ]]; then
    if [ $(program_is_installed "isohybrid") -eq 0 ]; then
        (apt-get -y install syslinux-utils > /dev/null 2>&1) & #depending on distro syslinux or syslinux-utils
        spinner $!
    fi
fi


# create working folders
echo " remastering your iso file"
mkdir -p $tmp
mkdir -p $tmp/iso_org
mkdir -p $tmp/iso_new

# mount the image
if grep -qs $tmp/iso_org /proc/mounts ; then
    echo " image is already mounted, continue"
else
    (mount -o loop $tmp/$download_file $tmp/iso_org > /dev/null 2>&1)
fi

# copy the iso contents to the working directory
(cp -rT $tmp/iso_org $tmp/iso_new > /dev/null 2>&1) &
spinner $!
echo "# D-I config version 2.0
# search path for the c32 support libraries (libcom32, libutil etc.)
LABEL Autoinstall
  menu label  Autoinstall
  kernel /install/vmlinuz
  append preseed/file=/cdrom/preseed.cfg debian-installer/locale=en_US keyboard-configuration/layoutcode=us console-setup/layoutcode=us languagechooser/language-name=English countrychooser/shortlist=US localechooser/supported-locales=en_US vga=788 initrd=/install/initrd.gz quiet -- auto=true priority=critical


path 
#include menu.cfg
#default vesamenu.c32
#prompt 0
timeout 10
ui gfxboot bootlogo
" > $tmp/iso_new/isolinux/isolinux.cfg
rm $tmp/iso_new/isolinux/txt.cfg

#You may have some syslinux boot issues due to file names, isolinux/syslinux move names may fix the errors
#mv $tmp/iso_new/isolinux/isolinux.cfg $tmp/iso_new/isolinux/syslinux.cfg
#mv $tmp/iso_new/isolinux mv $tmp/iso_new/syslinux
#cp $tmp/preseed.cfg $tmp/iso_new
# set the language for the installation menu
cd $tmp/iso_new
#echo en > $tmp/iso_new/isolinux/lang

# set late command
#late_command="chroot /target wget -O /home/$username/start.sh https://github.com/netson/ubuntu-unattended/raw/master/start.sh ;\
#    chroot /target chmod +x /home/$username/start.sh ;"
#set late command
late_command="chroot /target"
# copy any or the netson seed file to the iso
cp $tmp/$seed_file $tmp/iso_new/$seed_file
#cp -rT $tmp/$seed_file $tmp/iso_new/preseed/$seed_file

#installing applications
if [[ $nmapin == "yes" ]] || [[ $nmapin == "y" ]]; then
echo "d-i preseed/late_command string apt-install nmap vim-nox python3-pip" >> $tmp/iso_new/$seed_file
fi


# include firstrun script # I personally chose not to use this I will run the commands I choose
#echo "
# setup firstrun script
#d-i preseed/late_command                                    string      $late_command" >> $tmp/iso_new/preseed/$seed_file

# generate the password hash
#pwhash=$(echo $upassword | mkpasswd -s -m sha-512)
#rootpwhash=$(echo $rpassword | mkpasswd -s -m sha-512)


# update the seed file to reflect the users' choices
# calculate checksum for seed file
#seed_checksum=$(md5sum $tmp/iso_new/$seed_file)
#my own sed begins example to follow sed -ie 's/few/asd/g' hello.txt
sed -ie "s/pusername/$username/g" $tmp/iso_new/$seed_file
sed -ie "s/phostname/$hostname/g" $tmp/iso_new/$seed_file
sed -ie "s/pupassword/$upassword/g" $tmp/iso_new/$seed_file
sed -ie "s/prpassword/$rpassword/g" $tmp/iso_new/$seed_file
sed -ie "s/pdomain/$domain/g" $tmp/iso_new/$seed_file 
#sed -ie "s/pusername/$username/g" $tmp/iso_new/$seed_file xtra
# add the autoinstall option to the menu
#sed -i "/label install/ilabel autoinstall\n\
#  menu label ^Autoinstall NETSON Ubuntu Server\n\
#  kernel /install/vmlinuz\n\
#  append file=/cdrom/preseed/ubuntu-server.seed initrd=/install/initrd.gz auto=true priority=high preseed/file=/cdrom/preseed/netson.seed preseed/file/checksum=$seed_checksum --" $tmp/iso_new/isolinux/txt.cfg

echo " creating the remastered iso"
cd $tmp/iso_new
(mkisofs -D -r -V "Jeff's_UBUNTU" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o $tmp/$new_iso_name . > /dev/null 2>&1) &
spinner $!

# make iso bootable (for dd'ing to  USB stick)
if [[ $bootable == "yes" ]] || [[ $bootable == "y" ]]; then
    isohybrid $tmp/$new_iso_name
fi

if [[ $usedd == "yes" ]] || [[ $usedd == "y" ]]; then
  echo " Creating your bootable disk with dd"
  (dd if=$tmp/$new_iso_name of=$disk bs=512k) &
  spinner $!
fi


# cleanup
umount $tmp/iso_org
rm -rf $tmp/iso_new
rm -rf $tmp/iso_org

# print info to user
echo " -----"
echo " finished remastering your ubuntu iso file"
echo " the new file is located at: $tmp/$new_iso_name"
echo " your username is: $username"
echo " your password is: $upassword"
echo " your root passwod is : $rpassword"
echo " your hostname is: $hostname"
echo " your timezone is: $timezone"
echo

# unset vars
unset username
unset upassword
unset upassword2
unset rpassword
unset rpassword2
unset hostname
unset timezone
unset pwhash
unset rootpwhash
unset download_file
unset download_location
unset new_iso_name
unset tmp
unset seed_file
echo "this is end of file line 356"
